"""Shared production governance gate identifiers for audit-plan validation."""

from __future__ import annotations


PRODUCTION_READINESS_GATE_IDS = frozenset(
    {
        "provider_profile_ready",
        "provider_integration_ready",
        "outcome_dataset_configured",
        "outcome_dataset_gate_passed",
        "predictive_optimization_disabled",
        "provider_certification_ledger_available",
        "provider_certification_ledger_integrity",
        "provider_certification_ledger_covers_domains",
        "provider_certification_protocols_current",
        "provider_certification_request_receipts_current",
        "provider_certification_reference_contracts_current",
        "provider_certification_command_fingerprints_current",
        "provider_certification_receipts_current",
        "ziwei_qimen_calculation_basis_audit_contract",
        "astrology_ephemeris_audit_contract",
        "xuanze_rule_table_audit_contract",
        "release_manifest_ledger_integrity",
        "history_integrity_passed",
        "archive_integrity_passed",
        "capability_audit_available",
        "capability_audit_receipt_current",
        "implemented_evidence_materialized",
        "blocked_capability_coverage_complete",
        "known_gap_handoff_bundle_ready",
        "known_gap_resolution_plan_covered",
        "classical_source_refresh_ready",
        "classical_source_latest_refresh_receipt_present",
        "current_benchmark_passed",
        "benchmark_birthplaces_geocoded",
        "benchmark_deliberation_receipts_bound",
        "benchmark_annual_timeline_receipts_bound",
        "benchmark_monthly_luck_receipts_bound",
        "benchmark_auspicious_calendar_receipts_bound",
        "benchmark_external_payload_birth_matches",
        "benchmark_topic_confidence_boundaries",
        "benchmark_analyze_response_schema_valid",
        "production_gate_registry_current",
        "release_manifest_classical_source_receipt_coverage",
        "release_manifest_provider_action_plan_coverage",
        "release_manifest_external_payload_birth_match_coverage",
        "outcome_dataset_external_review_gate",
        "outcome_dataset_frozen_holdout_gate",
        "outcome_dataset_data_split_records_covered",
        "outcome_dataset_label_collection_pre_analysis_gate",
        "outcome_dataset_statistical_plan_preregistered",
    }
)
